k9s:
  cluster: bjorka
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - simple-pg
      - test-db
      - cnpg-system
      - argocd
      - all
      - default
      - test-sb
      - status
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
